name: app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_bloc: ^3.1.0
  bloc: ^3.0.0
  flutter:
    sdk: flutter
  http: any
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.3

flutter:

  uses-material-design: true

